apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "github-updater.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "github-updater.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "github-updater.name" . }}
    spec:
      containers:
        - name: github-updater
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-secrets
                  key: GITHUB_TOKEN
